### PR TITLE
Adding JBC generation to max10_10m08evk

### PR DESCRIPTION
**Pull request by gsteiert**
This adds JBC file generation to the MAX10 10M08 Evaluation Kit
This is to facilitate drag-n-drop programming with jbcuf2

### CODE REVIEW

**Comment by olofk** [comment]
Hmm... getting some merge conflicts here. Could you try rebasing to latest master?

**Comment by olofk** [comment]
Never mind. I think I sorted it out. Could you check on the master branch that I got it right before we close this?

**Comment by gsteiert** [comment]
It looks good and builds, thanks for the quick turn around.

**Comment by olofk** [comment]
Hmm... this was merged already, right?

**Pull request closed without merging**
