### PR TITLE
add support for Arrow SoCKit board

### PR DESCRIPTION
**Pull request by somhi**

### CODE REVIEW

**Comment by olofk** [comment]
Thanks, but I think this board is actually already supported, although the target is called `soc_kit` instead of `sockit`. Or are these two different ones?

**Comment by somhi** [comment]
I though the same, but then I looked at the pins and they are two different boards.  
soc_kit should be DE0-Nano-SoC Kit/Atlas-SoC Kit  https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&CategoryNo=165&No=941

SoCKit  is the Arrow board by Terasic  https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&CategoryNo=167&No=816

**Comment by olofk** [comment]
Ah ok. Good catch. I assumed it was the Arrow board too. That's the one I have as well.

But it gets more confusing now since there also already is a de0_nansoc. I think the soc_kit one should probably be removed but I need to dig into this to be sure.

Happy to add your contibution, but as we have seen some confusion already it would be great if you also could update README.md and add a link to your board

**Comment by somhi** [comment]
Readme.md updated!
Thanks

**Comment by olofk** [comment]
Excellent! Thanks for your contribution. Picked and pushed

**Pull request merged**
