### PR TITLE
Added support for Basys3

### PR DESCRIPTION
**Pull request by tyler-marr**
Specifically the right most LED

### CODE REVIEW

**Comment by olofk** [comment]
So I just noticed I got two PRs for the same board in less than a week with this and https://github.com/fusesoc/blinky/pull/53 What makes me a bit confused is that the two PRs use different part numbers. Did @tyler-marr or @rafaelnp get it wrong, or do both work?

**Comment by tyler-marr** [comment]
I can check the on the board on monday if both work but I can confrim "xc7a35tcpg236-1" works and I got the value from Vivado on a Basys3 project I had. I cant seem to find a reference to the "xc7a35ticpg236" varient however.

**Comment by olofk** [comment]
Thanks for your contribution and the additional info. I decided to go with #53 since that had the confirmed part number and also an entry in the readme file.

**Comment by rafaelnp** [comment]
@olofk It worked on my Basys3 board. I took a look at the [digilent repo]( https://github.com/Digilent/vivado-boards/blob/18d7d68c415e31afdcdcd56ad2d281dca1e51d6c/new/board_files/basys3/C.0/board.xml#L9),  and there it mentions ` xc7a35tcpg236-1`.

**Pull request closed without merging**
