### PR TITLE
Add support for Saanlima pipistrello spartan6 LX45

### PR DESCRIPTION
**Pull request by trabucayre**
Saanlima pipistrello board based on spartan6 LX45
http://pipistrello.saanlima.com/index.php?title=Welcome_to_Pipistrello

### CODE REVIEW

**Comment by olofk** [comment]
You know how to do this by now, so I have no complaints :) Thanks again for providing support for more boards.

Btw, in case you also want to run a RISC-V core on your boards, check out https://github.com/olofk/serv/tree/master/rtl It's pretty similar to adding blinky support. Just need an UART output and preferably a 16MHz clock.

**Comment by trabucayre** [comment]
Funny because it's exactly I do now. I know serv too (arty A7) and I'm working on adding my board to this :)

**Comment by olofk** [comment]
Ah, I had forgotten that it was you who did the Arty port :)

Any of the spartan6 boards going in? I'm curious to know if it works with ISE (slightly related, I'm about to add support for doing synthesis with yosys in the ISE backend)

Anyway, looking forward to more board support for serv and if you send a PR tonight I might even have time to add it to my SERV presentation tomorrow :) https://www.meetup.com/Munich-RISC-V-Meetup-Group/events/269686190/

**Comment by trabucayre** [comment]
ISE fails to build serv with:
```
System function call clog2 is not allowed here
```
I think all is done for pipistrello support in serv but unable to build it :-(
So I have to delay the PR... :-( again

**Comment by olofk** [comment]
If the problem is with a localparam, you could try changing it to a parameter to see if this helps. I have a vague memory of an ISE bug related to this. The ISE parser is awful and the long term solution is to just use yosys instead. If you can't find a workaround I'll let you know when the yosys support is added to the ISE backend

**Comment by trabucayre** [comment]
True!
I have hardcoded some locaparam xxx = $clog2(yyy); the build finish with success. Currently blinky.hex is working, now I try uart for final check.
Butn anyway, I need to wait due to issue with synthesis part...

**Pull request merged**
