### PR TITLE
Apf27

### PR DESCRIPTION
**Pull request by Martoni**
Adding [apf27](http://www.opossom.com/english/products-processor_boards-apf27.html) platform, from armadeus system.

### CODE REVIEW

**Comment by olofk** [comment]
I can't get this to work. Seems like ISE fails to part the $clog2 statement. I wonder if it uses another parser for Spartan3 for some reason

**Comment by Martoni** [comment]
In fact ... I have exactly the same problem. According to Xilinx, the bug should be solved since XST 14.1.
But I have the bug with XST 14.7 ...

**Comment by olofk** [comment]
ok, I fixed it. I'm amending your patch with the fix. Hope that's ok. Otherwise, let me know

Picked and pushed.

**Comment by Martoni** [comment]
Thanks, its works for me \o/
My led is blinking.

**Comment by olofk** [comment]
That's all that matters in the end :)

**Comment by Martoni** [comment]
Of course.
I have two other platform do add : 
- APF51 : should not be that difficult
- APF6_SP : should be trickier because the clock source for FPGA come from PCIe hardware block in CycloneV

But I do not have time to do it now. Will see.

**Pull request closed without merging**
